[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tinychat"
version = "0.1.0"
description = "A simple open source framework for conversational AI."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.0",
    "anthropic>=0.69.0",
    "loguru>=0.7.3",
    "openai>=2.3.0",
    "python-dotenv>=1.1.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.0.0",
    "pytest>=8.4.2",
    "pytest-aiohttp>=1.1.0",
    "pytest-asyncio>=1.2.0",
    "ruff>=0.14.0",
]

[tool.uv.workspace]
members = [
    "tinychat/examples/app",
]
